### ISSUE TITLE
Zvednutý rámeček o jednu vrstvu

### ISSUE THREAD

**Issue by montycz** [janlouda/marsalaspion#1]
Ahoj, bylo by možno usadit zadní rámeček u holderu tak, aby seděl hned na podložce? Při slicnutí je o jednu vrstvu zvednutý.
![holder](https://user-images.githubusercontent.com/59710283/72106195-31311080-332f-11ea-800b-2cf387391292.png)

**Comment by janlouda** [comment]
Opraveno.

**Comment by montycz** [comment]
Paráda, vyzkouším. Díky
